Resources:
  HitsFF5AF8CD:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      KeySchema:
        - AttributeName: path
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: path
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      'aws:cdk:path': the-dynamo-flow-stack/Hits/Resource
  DynamoLambdaHandlerServiceRole4C867B01:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - !Join 
          - ''
          - - 'arn:'
            - !Ref 'AWS::Partition'
            - ':iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
    Metadata:
      'aws:cdk:path': the-dynamo-flow-stack/DynamoLambdaHandler/ServiceRole/Resource
  DynamoLambdaHandlerServiceRoleDefaultPolicy2B40B090:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 'xray:PutTraceSegments'
              - 'xray:PutTelemetryRecords'
            Effect: Allow
            Resource: '*'
          - Action:
              - 'dynamodb:BatchGetItem'
              - 'dynamodb:GetRecords'
              - 'dynamodb:GetShardIterator'
              - 'dynamodb:Query'
              - 'dynamodb:GetItem'
              - 'dynamodb:Scan'
              - 'dynamodb:BatchWriteItem'
              - 'dynamodb:PutItem'
              - 'dynamodb:UpdateItem'
              - 'dynamodb:DeleteItem'
            Effect: Allow
            Resource:
              - !GetAtt 
                - HitsFF5AF8CD
                - Arn
              - !Ref 'AWS::NoValue'
        Version: 2012-10-17
      PolicyName: DynamoLambdaHandlerServiceRoleDefaultPolicy2B40B090
      Roles:
        - !Ref DynamoLambdaHandlerServiceRole4C867B01
    Metadata:
      'aws:cdk:path': >-
        the-dynamo-flow-stack/DynamoLambdaHandler/ServiceRole/DefaultPolicy/Resource
  DynamoLambdaHandlerFB6EB814:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: !Ref >-
          AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116S3Bucket8173FDE2
        S3Key: !Join 
          - ''
          - - !Select 
              - 0
              - !Split 
                - '||'
                - !Ref >-
                  AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116S3VersionKey4EBDDFB9
            - !Select 
              - 1
              - !Split 
                - '||'
                - !Ref >-
                  AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116S3VersionKey4EBDDFB9
      Handler: dynamo.handler
      Role: !GetAtt 
        - DynamoLambdaHandlerServiceRole4C867B01
        - Arn
      Runtime: nodejs12.x
      Environment:
        Variables:
          HITS_TABLE_NAME: !Ref HitsFF5AF8CD
      TracingConfig:
        Mode: Active
    DependsOn:
      - DynamoLambdaHandlerServiceRoleDefaultPolicy2B40B090
      - DynamoLambdaHandlerServiceRole4C867B01
    Metadata:
      'aws:cdk:path': the-dynamo-flow-stack/DynamoLambdaHandler/Resource
      'aws:asset:path': asset.86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116
      'aws:asset:property': Code
  DynamoLambdaHandlerAllowInvokethedynamoflowstackSNSTopicF9AC44191B4552DC:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt 
        - DynamoLambdaHandlerFB6EB814
        - Arn
      Principal: sns.amazonaws.com
      SourceArn: !ImportValue >-
        the-xray-tracer:ExportsOutputRefTheXRayTracerSnsFanOutTopicDE7E70F8D479F0D6
    Metadata:
      'aws:cdk:path': >-
        the-dynamo-flow-stack/DynamoLambdaHandler/AllowInvoke:thedynamoflowstackSNSTopicF9AC4419
  DynamoLambdaHandlerSNSTopic27AC0D9B:
    Type: 'AWS::SNS::Subscription'
    Properties:
      Protocol: lambda
      TopicArn: !ImportValue >-
        the-xray-tracer:ExportsOutputRefTheXRayTracerSnsFanOutTopicDE7E70F8D479F0D6
      Endpoint: !GetAtt 
        - DynamoLambdaHandlerFB6EB814
        - Arn
    Metadata:
      'aws:cdk:path': the-dynamo-flow-stack/DynamoLambdaHandler/SNSTopic/Resource
Parameters:
  AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116S3Bucket8173FDE2:
    Type: String
    Description: >-
      S3 bucket for asset
      "86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116"
  AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116S3VersionKey4EBDDFB9:
    Type: String
    Description: >-
      S3 key for asset version
      "86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116"
  AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116ArtifactHashF154A969:
    Type: String
    Description: >-
      Artifact hash for asset
      "86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116"
