Resources:
  httpLambdaHandlerServiceRole01D49A7D:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - !Join 
          - ''
          - - 'arn:'
            - !Ref 'AWS::Partition'
            - ':iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
    Metadata:
      'aws:cdk:path': the-http-flow-stack/httpLambdaHandler/ServiceRole/Resource
  httpLambdaHandlerServiceRoleDefaultPolicy1B465FFF:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 'xray:PutTraceSegments'
              - 'xray:PutTelemetryRecords'
            Effect: Allow
            Resource: '*'
        Version: 2012-10-17
      PolicyName: httpLambdaHandlerServiceRoleDefaultPolicy1B465FFF
      Roles:
        - !Ref httpLambdaHandlerServiceRole01D49A7D
    Metadata:
      'aws:cdk:path': the-http-flow-stack/httpLambdaHandler/ServiceRole/DefaultPolicy/Resource
  httpLambdaHandler66D9C9A8:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: !Ref >-
          AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116S3Bucket8173FDE2
        S3Key: !Join 
          - ''
          - - !Select 
              - 0
              - !Split 
                - '||'
                - !Ref >-
                  AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116S3VersionKey4EBDDFB9
            - !Select 
              - 1
              - !Split 
                - '||'
                - !Ref >-
                  AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116S3VersionKey4EBDDFB9
      Handler: http.handler
      Role: !GetAtt 
        - httpLambdaHandlerServiceRole01D49A7D
        - Arn
      Runtime: nodejs12.x
      TracingConfig:
        Mode: Active
    DependsOn:
      - httpLambdaHandlerServiceRoleDefaultPolicy1B465FFF
      - httpLambdaHandlerServiceRole01D49A7D
    Metadata:
      'aws:cdk:path': the-http-flow-stack/httpLambdaHandler/Resource
      'aws:asset:path': asset.86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116
      'aws:asset:property': Code
  httpLambdaHandlerAllowInvokethehttpflowstackSNSTopic133195DFDBAC33C8:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt 
        - httpLambdaHandler66D9C9A8
        - Arn
      Principal: sns.amazonaws.com
      SourceArn: !ImportValue >-
        the-xray-tracer:ExportsOutputRefTheXRayTracerSnsFanOutTopicDE7E70F8D479F0D6
    Metadata:
      'aws:cdk:path': >-
        the-http-flow-stack/httpLambdaHandler/AllowInvoke:thehttpflowstackSNSTopic133195DF
  httpLambdaHandlerSNSTopicEE70E0D4:
    Type: 'AWS::SNS::Subscription'
    Properties:
      Protocol: lambda
      TopicArn: !ImportValue >-
        the-xray-tracer:ExportsOutputRefTheXRayTracerSnsFanOutTopicDE7E70F8D479F0D6
      Endpoint: !GetAtt 
        - httpLambdaHandler66D9C9A8
        - Arn
    Metadata:
      'aws:cdk:path': the-http-flow-stack/httpLambdaHandler/SNSTopic/Resource
Parameters:
  AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116S3Bucket8173FDE2:
    Type: String
    Description: >-
      S3 bucket for asset
      "86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116"
  AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116S3VersionKey4EBDDFB9:
    Type: String
    Description: >-
      S3 key for asset version
      "86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116"
  AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116ArtifactHashF154A969:
    Type: String
    Description: >-
      Artifact hash for asset
      "86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116"
