Resources:
  TheXRayTracerSnsTopicCCE2005E:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: The XRay Tracer CDK Pattern Topic
    Metadata:
      'aws:cdk:path': the-sns-flow-stack/TheXRayTracerSnsTopic/Resource
  snsLambdaHandlerServiceRole7F428B88:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - !Join 
          - ''
          - - 'arn:'
            - !Ref 'AWS::Partition'
            - ':iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
    Metadata:
      'aws:cdk:path': the-sns-flow-stack/snsLambdaHandler/ServiceRole/Resource
  snsLambdaHandlerServiceRoleDefaultPolicy80707B6B:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 'xray:PutTraceSegments'
              - 'xray:PutTelemetryRecords'
            Effect: Allow
            Resource: '*'
          - Action: 'sns:Publish'
            Effect: Allow
            Resource: !Ref TheXRayTracerSnsTopicCCE2005E
        Version: 2012-10-17
      PolicyName: snsLambdaHandlerServiceRoleDefaultPolicy80707B6B
      Roles:
        - !Ref snsLambdaHandlerServiceRole7F428B88
    Metadata:
      'aws:cdk:path': the-sns-flow-stack/snsLambdaHandler/ServiceRole/DefaultPolicy/Resource
  snsLambdaHandlerE7B0ABE3:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: !Ref >-
          AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116S3Bucket8173FDE2
        S3Key: !Join 
          - ''
          - - !Select 
              - 0
              - !Split 
                - '||'
                - !Ref >-
                  AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116S3VersionKey4EBDDFB9
            - !Select 
              - 1
              - !Split 
                - '||'
                - !Ref >-
                  AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116S3VersionKey4EBDDFB9
      Handler: sns_publish.handler
      Role: !GetAtt 
        - snsLambdaHandlerServiceRole7F428B88
        - Arn
      Runtime: nodejs12.x
      Environment:
        Variables:
          TOPIC_ARN: !Ref TheXRayTracerSnsTopicCCE2005E
      TracingConfig:
        Mode: Active
    DependsOn:
      - snsLambdaHandlerServiceRoleDefaultPolicy80707B6B
      - snsLambdaHandlerServiceRole7F428B88
    Metadata:
      'aws:cdk:path': the-sns-flow-stack/snsLambdaHandler/Resource
      'aws:asset:path': asset.86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116
      'aws:asset:property': Code
  snsLambdaHandlerAllowInvokethesnsflowstackSNSTopicD9ECACE478D5EE3D:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt 
        - snsLambdaHandlerE7B0ABE3
        - Arn
      Principal: sns.amazonaws.com
      SourceArn: !ImportValue >-
        the-xray-tracer:ExportsOutputRefTheXRayTracerSnsFanOutTopicDE7E70F8D479F0D6
    Metadata:
      'aws:cdk:path': >-
        the-sns-flow-stack/snsLambdaHandler/AllowInvoke:thesnsflowstackSNSTopicD9ECACE4
  snsLambdaHandlerSNSTopic3B2CFF1D:
    Type: 'AWS::SNS::Subscription'
    Properties:
      Protocol: lambda
      TopicArn: !ImportValue >-
        the-xray-tracer:ExportsOutputRefTheXRayTracerSnsFanOutTopicDE7E70F8D479F0D6
      Endpoint: !GetAtt 
        - snsLambdaHandlerE7B0ABE3
        - Arn
    Metadata:
      'aws:cdk:path': the-sns-flow-stack/snsLambdaHandler/SNSTopic/Resource
  snsSubscriptionLambdaHandlerServiceRole215E543C:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - !Join 
          - ''
          - - 'arn:'
            - !Ref 'AWS::Partition'
            - ':iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
    Metadata:
      'aws:cdk:path': the-sns-flow-stack/snsSubscriptionLambdaHandler/ServiceRole/Resource
  snsSubscriptionLambdaHandlerServiceRoleDefaultPolicy23353421:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 'xray:PutTraceSegments'
              - 'xray:PutTelemetryRecords'
            Effect: Allow
            Resource: '*'
        Version: 2012-10-17
      PolicyName: snsSubscriptionLambdaHandlerServiceRoleDefaultPolicy23353421
      Roles:
        - !Ref snsSubscriptionLambdaHandlerServiceRole215E543C
    Metadata:
      'aws:cdk:path': >-
        the-sns-flow-stack/snsSubscriptionLambdaHandler/ServiceRole/DefaultPolicy/Resource
  snsSubscriptionLambdaHandler68619CD8:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: !Ref >-
          AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116S3Bucket8173FDE2
        S3Key: !Join 
          - ''
          - - !Select 
              - 0
              - !Split 
                - '||'
                - !Ref >-
                  AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116S3VersionKey4EBDDFB9
            - !Select 
              - 1
              - !Split 
                - '||'
                - !Ref >-
                  AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116S3VersionKey4EBDDFB9
      Handler: sns_subscribe.handler
      Role: !GetAtt 
        - snsSubscriptionLambdaHandlerServiceRole215E543C
        - Arn
      Runtime: nodejs12.x
      TracingConfig:
        Mode: Active
    DependsOn:
      - snsSubscriptionLambdaHandlerServiceRoleDefaultPolicy23353421
      - snsSubscriptionLambdaHandlerServiceRole215E543C
    Metadata:
      'aws:cdk:path': the-sns-flow-stack/snsSubscriptionLambdaHandler/Resource
      'aws:asset:path': asset.86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116
      'aws:asset:property': Code
  snsSubscriptionLambdaHandlerAllowInvokethesnsflowstackTheXRayTracerSnsTopic247FEE119CD4AA4A:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt 
        - snsSubscriptionLambdaHandler68619CD8
        - Arn
      Principal: sns.amazonaws.com
      SourceArn: !Ref TheXRayTracerSnsTopicCCE2005E
    Metadata:
      'aws:cdk:path': >-
        the-sns-flow-stack/snsSubscriptionLambdaHandler/AllowInvoke:thesnsflowstackTheXRayTracerSnsTopic247FEE11
  snsSubscriptionLambdaHandlerTheXRayTracerSnsTopic6FDB75DD:
    Type: 'AWS::SNS::Subscription'
    Properties:
      Protocol: lambda
      TopicArn: !Ref TheXRayTracerSnsTopicCCE2005E
      Endpoint: !GetAtt 
        - snsSubscriptionLambdaHandler68619CD8
        - Arn
    Metadata:
      'aws:cdk:path': >-
        the-sns-flow-stack/snsSubscriptionLambdaHandler/TheXRayTracerSnsTopic/Resource
Parameters:
  AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116S3Bucket8173FDE2:
    Type: String
    Description: >-
      S3 bucket for asset
      "86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116"
  AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116S3VersionKey4EBDDFB9:
    Type: String
    Description: >-
      S3 key for asset version
      "86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116"
  AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116ArtifactHashF154A969:
    Type: String
    Description: >-
      Artifact hash for asset
      "86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116"
