Resources:
  RDSPublishQueue2BEA1A7F:
    Type: 'AWS::SQS::Queue'
    Properties:
      VisibilityTimeout: 300
    Metadata:
      'aws:cdk:path': the-sqs-flow-stack/RDSPublishQueue/Resource
  sqsLambdaHandlerServiceRole2F57B7B5:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - !Join 
          - ''
          - - 'arn:'
            - !Ref 'AWS::Partition'
            - ':iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
    Metadata:
      'aws:cdk:path': the-sqs-flow-stack/sqsLambdaHandler/ServiceRole/Resource
  sqsLambdaHandlerServiceRoleDefaultPolicyBB0CE949:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 'xray:PutTraceSegments'
              - 'xray:PutTelemetryRecords'
            Effect: Allow
            Resource: '*'
          - Action:
              - 'sqs:SendMessage'
              - 'sqs:GetQueueAttributes'
              - 'sqs:GetQueueUrl'
            Effect: Allow
            Resource: !GetAtt 
              - RDSPublishQueue2BEA1A7F
              - Arn
        Version: 2012-10-17
      PolicyName: sqsLambdaHandlerServiceRoleDefaultPolicyBB0CE949
      Roles:
        - !Ref sqsLambdaHandlerServiceRole2F57B7B5
    Metadata:
      'aws:cdk:path': the-sqs-flow-stack/sqsLambdaHandler/ServiceRole/DefaultPolicy/Resource
  sqsLambdaHandler0DD5DF9B:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: !Ref >-
          AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116S3Bucket8173FDE2
        S3Key: !Join 
          - ''
          - - !Select 
              - 0
              - !Split 
                - '||'
                - !Ref >-
                  AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116S3VersionKey4EBDDFB9
            - !Select 
              - 1
              - !Split 
                - '||'
                - !Ref >-
                  AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116S3VersionKey4EBDDFB9
      Handler: sqs.handler
      Role: !GetAtt 
        - sqsLambdaHandlerServiceRole2F57B7B5
        - Arn
      Runtime: nodejs12.x
      Environment:
        Variables:
          SQS_URL: !Ref RDSPublishQueue2BEA1A7F
      TracingConfig:
        Mode: Active
    DependsOn:
      - sqsLambdaHandlerServiceRoleDefaultPolicyBB0CE949
      - sqsLambdaHandlerServiceRole2F57B7B5
    Metadata:
      'aws:cdk:path': the-sqs-flow-stack/sqsLambdaHandler/Resource
      'aws:asset:path': asset.86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116
      'aws:asset:property': Code
  sqsLambdaHandlerAllowInvokethesqsflowstackSNSTopicBC35ECF8039FB39D:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt 
        - sqsLambdaHandler0DD5DF9B
        - Arn
      Principal: sns.amazonaws.com
      SourceArn: !ImportValue >-
        the-xray-tracer:ExportsOutputRefTheXRayTracerSnsFanOutTopicDE7E70F8D479F0D6
    Metadata:
      'aws:cdk:path': >-
        the-sqs-flow-stack/sqsLambdaHandler/AllowInvoke:thesqsflowstackSNSTopicBC35ECF8
  sqsLambdaHandlerSNSTopicC33599CE:
    Type: 'AWS::SNS::Subscription'
    Properties:
      Protocol: lambda
      TopicArn: !ImportValue >-
        the-xray-tracer:ExportsOutputRefTheXRayTracerSnsFanOutTopicDE7E70F8D479F0D6
      Endpoint: !GetAtt 
        - sqsLambdaHandler0DD5DF9B
        - Arn
    Metadata:
      'aws:cdk:path': the-sqs-flow-stack/sqsLambdaHandler/SNSTopic/Resource
  sqsSubscribeLambdaHandlerServiceRole8F070FD3:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - !Join 
          - ''
          - - 'arn:'
            - !Ref 'AWS::Partition'
            - ':iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
    Metadata:
      'aws:cdk:path': the-sqs-flow-stack/sqsSubscribeLambdaHandler/ServiceRole/Resource
  sqsSubscribeLambdaHandlerServiceRoleDefaultPolicyFCDD3C26:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 'xray:PutTraceSegments'
              - 'xray:PutTelemetryRecords'
            Effect: Allow
            Resource: '*'
          - Action:
              - 'sqs:ReceiveMessage'
              - 'sqs:ChangeMessageVisibility'
              - 'sqs:GetQueueUrl'
              - 'sqs:DeleteMessage'
              - 'sqs:GetQueueAttributes'
            Effect: Allow
            Resource: !GetAtt 
              - RDSPublishQueue2BEA1A7F
              - Arn
        Version: 2012-10-17
      PolicyName: sqsSubscribeLambdaHandlerServiceRoleDefaultPolicyFCDD3C26
      Roles:
        - !Ref sqsSubscribeLambdaHandlerServiceRole8F070FD3
    Metadata:
      'aws:cdk:path': >-
        the-sqs-flow-stack/sqsSubscribeLambdaHandler/ServiceRole/DefaultPolicy/Resource
  sqsSubscribeLambdaHandlerD66392B8:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: !Ref >-
          AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116S3Bucket8173FDE2
        S3Key: !Join 
          - ''
          - - !Select 
              - 0
              - !Split 
                - '||'
                - !Ref >-
                  AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116S3VersionKey4EBDDFB9
            - !Select 
              - 1
              - !Split 
                - '||'
                - !Ref >-
                  AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116S3VersionKey4EBDDFB9
      Handler: sqs_subscribe.handler
      Role: !GetAtt 
        - sqsSubscribeLambdaHandlerServiceRole8F070FD3
        - Arn
      Runtime: nodejs12.x
      TracingConfig:
        Mode: Active
    DependsOn:
      - sqsSubscribeLambdaHandlerServiceRoleDefaultPolicyFCDD3C26
      - sqsSubscribeLambdaHandlerServiceRole8F070FD3
    Metadata:
      'aws:cdk:path': the-sqs-flow-stack/sqsSubscribeLambdaHandler/Resource
      'aws:asset:path': asset.86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116
      'aws:asset:property': Code
  sqsSubscribeLambdaHandlerSqsEventSourcethesqsflowstackRDSPublishQueue01803DC83ACA5976:
    Type: 'AWS::Lambda::EventSourceMapping'
    Properties:
      EventSourceArn: !GetAtt 
        - RDSPublishQueue2BEA1A7F
        - Arn
      FunctionName: !Ref sqsSubscribeLambdaHandlerD66392B8
    Metadata:
      'aws:cdk:path': >-
        the-sqs-flow-stack/sqsSubscribeLambdaHandler/SqsEventSource:thesqsflowstackRDSPublishQueue01803DC8/Resource
Parameters:
  AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116S3Bucket8173FDE2:
    Type: String
    Description: >-
      S3 bucket for asset
      "86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116"
  AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116S3VersionKey4EBDDFB9:
    Type: String
    Description: >-
      S3 key for asset version
      "86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116"
  AssetParameters86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116ArtifactHashF154A969:
    Type: String
    Description: >-
      Artifact hash for asset
      "86de130d5456c41c39cc041f23d5d7fc0d0d34a0ec558bd6e3ac281519f3b116"
