Resources:
  destinedLambdaServiceRole87608B6F:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: TheDestinedLambdaStack/destinedLambda/ServiceRole/Resource
  destinedLambdaServiceRoleDefaultPolicy9D15647D:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: events:PutEvents
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: destinedLambdaServiceRoleDefaultPolicy9D15647D
      Roles:
        - Ref: destinedLambdaServiceRole87608B6F
    Metadata:
      aws:cdk:path: TheDestinedLambdaStack/destinedLambda/ServiceRole/DefaultPolicy/Resource
  destinedLambda8DF776BB:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersa6a7a2d7ada1af86b128fe5f1044082417d163dd81d3bc050192f500193db154S3Bucket3C1E61AF
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersa6a7a2d7ada1af86b128fe5f1044082417d163dd81d3bc050192f500193db154S3VersionKey35C816E2
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersa6a7a2d7ada1af86b128fe5f1044082417d163dd81d3bc050192f500193db154S3VersionKey35C816E2
      Handler: destinedLambda.handler
      Role:
        Fn::GetAtt:
          - destinedLambdaServiceRole87608B6F
          - Arn
      Runtime: nodejs12.x
    DependsOn:
      - destinedLambdaServiceRoleDefaultPolicy9D15647D
      - destinedLambdaServiceRole87608B6F
    Metadata:
      aws:cdk:path: TheDestinedLambdaStack/destinedLambda/Resource
      aws:asset:path: asset.a6a7a2d7ada1af86b128fe5f1044082417d163dd81d3bc050192f500193db154
      aws:asset:property: Code
  destinedLambdaEventInvokeConfig3CA2AF7E:
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      FunctionName:
        Ref: destinedLambda8DF776BB
      Qualifier: $LATEST
      DestinationConfig:
        OnSuccess:
          Destination:
            Fn::Join:
              - ""
              - - "arn:"
                - Ref: AWS::Partition
                - ":events:"
                - Ref: AWS::Region
                - ":"
                - Ref: AWS::AccountId
                - :event-bus/default
    Metadata:
      aws:cdk:path: TheDestinedLambdaStack/destinedLambda/EventInvokeConfig/Resource
  ObserveLambdaHandlerServiceRole040C69BA:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: TheDestinedLambdaStack/ObserveLambdaHandler/ServiceRole/Resource
  ObserveLambdaHandler685FFDBB:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersa6a7a2d7ada1af86b128fe5f1044082417d163dd81d3bc050192f500193db154S3Bucket3C1E61AF
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersa6a7a2d7ada1af86b128fe5f1044082417d163dd81d3bc050192f500193db154S3VersionKey35C816E2
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersa6a7a2d7ada1af86b128fe5f1044082417d163dd81d3bc050192f500193db154S3VersionKey35C816E2
      Handler: observe.handler
      Role:
        Fn::GetAtt:
          - ObserveLambdaHandlerServiceRole040C69BA
          - Arn
      Runtime: nodejs12.x
      Timeout: 3
    DependsOn:
      - ObserveLambdaHandlerServiceRole040C69BA
    Metadata:
      aws:cdk:path: TheDestinedLambdaStack/ObserveLambdaHandler/Resource
      aws:asset:path: asset.a6a7a2d7ada1af86b128fe5f1044082417d163dd81d3bc050192f500193db154
      aws:asset:property: Code
  ObserveLambdaHandlerAllowEventRuleTheDestinedLambdaStackobserveRule1315CAFB065DC0FA:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - ObserveLambdaHandler685FFDBB
          - Arn
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - observeRule9CF2E16C
          - Arn
    Metadata:
      aws:cdk:path: TheDestinedLambdaStack/ObserveLambdaHandler/AllowEventRuleTheDestinedLambdaStackobserveRule1315CAFB
  observeRule9CF2E16C:
    Type: AWS::Events::Rule
    Properties:
      Description: all events are caught here and logged centrally
      EventPattern:
        source:
          - cdkpatterns.the-eventbridge-etl
      State: ENABLED
      Targets:
        - Arn:
            Fn::GetAtt:
              - ObserveLambdaHandler685FFDBB
              - Arn
          Id: Target0
    Metadata:
      aws:cdk:path: TheDestinedLambdaStack/observeRule/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.30.0,@aws-cdk/assets=1.30.0,@aws-cdk/aws-applicationautoscaling=1.30.0,@aws-cdk/aws-autoscaling=1.30.0,@aws-cdk/aws-autoscaling-common=1.30.0,@aws-cdk/aws-autoscaling-hooktargets=1.30.0,@aws-cdk/aws-cloudwatch=1.30.0,@aws-cdk/aws-ec2=1.30.0,@aws-cdk/aws-ecr=1.30.0,@aws-cdk/aws-ecr-assets=1.30.0,@aws-cdk/aws-ecs=1.30.0,@aws-cdk/aws-elasticloadbalancingv2=1.30.0,@aws-cdk/aws-events=1.30.0,@aws-cdk/aws-events-targets=1.30.0,@aws-cdk/aws-iam=1.30.0,@aws-cdk/aws-kms=1.30.0,@aws-cdk/aws-lambda=1.30.0,@aws-cdk/aws-lambda-destinations=1.30.0,@aws-cdk/aws-logs=1.30.0,@aws-cdk/aws-s3=1.30.0,@aws-cdk/aws-s3-assets=1.30.0,@aws-cdk/aws-servicediscovery=1.30.0,@aws-cdk/aws-sns=1.30.0,@aws-cdk/aws-sns-subscriptions=1.30.0,@aws-cdk/aws-sqs=1.30.0,@aws-cdk/aws-ssm=1.30.0,@aws-cdk/core=1.30.0,@aws-cdk/cx-api=1.30.0,@aws-cdk/region-info=1.30.0,jsii-runtime=node.js/v11.10.0
    Condition: CDKMetadataAvailable
Parameters:
  AssetParametersa6a7a2d7ada1af86b128fe5f1044082417d163dd81d3bc050192f500193db154S3Bucket3C1E61AF:
    Type: String
    Description: S3 bucket for asset "a6a7a2d7ada1af86b128fe5f1044082417d163dd81d3bc050192f500193db154"
  AssetParametersa6a7a2d7ada1af86b128fe5f1044082417d163dd81d3bc050192f500193db154S3VersionKey35C816E2:
    Type: String
    Description: S3 key for asset version "a6a7a2d7ada1af86b128fe5f1044082417d163dd81d3bc050192f500193db154"
  AssetParametersa6a7a2d7ada1af86b128fe5f1044082417d163dd81d3bc050192f500193db154ArtifactHashEF3832F1:
    Type: String
    Description: Artifact hash for asset "a6a7a2d7ada1af86b128fe5f1044082417d163dd81d3bc050192f500193db154"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

