Resources:
  HitsFF5AF8CD:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      KeySchema:
        - AttributeName: path
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: path
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      'aws:cdk:path': TheXrayDynamoFlow/Hits/Resource
  DynamoLambdaHandlerServiceRole4C867B01:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - !Join 
          - ''
          - - 'arn:'
            - !Ref 'AWS::Partition'
            - ':iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
    Metadata:
      'aws:cdk:path': TheXrayDynamoFlow/DynamoLambdaHandler/ServiceRole/Resource
  DynamoLambdaHandlerServiceRoleDefaultPolicy2B40B090:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 'xray:PutTraceSegments'
              - 'xray:PutTelemetryRecords'
            Effect: Allow
            Resource: '*'
          - Action:
              - 'dynamodb:BatchGetItem'
              - 'dynamodb:GetRecords'
              - 'dynamodb:GetShardIterator'
              - 'dynamodb:Query'
              - 'dynamodb:GetItem'
              - 'dynamodb:Scan'
              - 'dynamodb:BatchWriteItem'
              - 'dynamodb:PutItem'
              - 'dynamodb:UpdateItem'
              - 'dynamodb:DeleteItem'
            Effect: Allow
            Resource:
              - !GetAtt 
                - HitsFF5AF8CD
                - Arn
              - !Ref 'AWS::NoValue'
        Version: 2012-10-17
      PolicyName: DynamoLambdaHandlerServiceRoleDefaultPolicy2B40B090
      Roles:
        - !Ref DynamoLambdaHandlerServiceRole4C867B01
    Metadata:
      'aws:cdk:path': TheXrayDynamoFlow/DynamoLambdaHandler/ServiceRole/DefaultPolicy/Resource
  DynamoLambdaHandlerFB6EB814:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: !Ref >-
          AssetParameters4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04bS3BucketFEB1737B
        S3Key: !Join 
          - ''
          - - !Select 
              - 0
              - !Split 
                - '||'
                - !Ref >-
                  AssetParameters4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04bS3VersionKey433D325F
            - !Select 
              - 1
              - !Split 
                - '||'
                - !Ref >-
                  AssetParameters4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04bS3VersionKey433D325F
      Handler: dynamo.handler
      Role: !GetAtt 
        - DynamoLambdaHandlerServiceRole4C867B01
        - Arn
      Runtime: nodejs12.x
      Environment:
        Variables:
          HITS_TABLE_NAME: !Ref HitsFF5AF8CD
      TracingConfig:
        Mode: Active
    DependsOn:
      - DynamoLambdaHandlerServiceRoleDefaultPolicy2B40B090
      - DynamoLambdaHandlerServiceRole4C867B01
    Metadata:
      'aws:cdk:path': TheXrayDynamoFlow/DynamoLambdaHandler/Resource
      'aws:asset:path': asset.4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04b
      'aws:asset:property': Code
  DynamoLambdaHandlerAllowInvokeTheXrayDynamoFlowSNSTopicCD4F86C04F3B929A:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt 
        - DynamoLambdaHandlerFB6EB814
        - Arn
      Principal: sns.amazonaws.com
      SourceArn: !ImportValue >-
        TheXrayTracerStack:ExportsOutputRefTheXRayTracerSnsFanOutTopicDE7E70F8D479F0D6
    Metadata:
      'aws:cdk:path': >-
        TheXrayDynamoFlow/DynamoLambdaHandler/AllowInvoke:TheXrayDynamoFlowSNSTopicCD4F86C0
  DynamoLambdaHandlerSNSTopic27AC0D9B:
    Type: 'AWS::SNS::Subscription'
    Properties:
      Protocol: lambda
      TopicArn: !ImportValue >-
        TheXrayTracerStack:ExportsOutputRefTheXRayTracerSnsFanOutTopicDE7E70F8D479F0D6
      Endpoint: !GetAtt 
        - DynamoLambdaHandlerFB6EB814
        - Arn
    Metadata:
      'aws:cdk:path': TheXrayDynamoFlow/DynamoLambdaHandler/SNSTopic/Resource
Parameters:
  AssetParameters4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04bS3BucketFEB1737B:
    Type: String
    Description: >-
      S3 bucket for asset
      "4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04b"
  AssetParameters4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04bS3VersionKey433D325F:
    Type: String
    Description: >-
      S3 key for asset version
      "4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04b"
  AssetParameters4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04bArtifactHash92535D2D:
    Type: String
    Description: >-
      Artifact hash for asset
      "4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04b"
