Resources:
  httpLambdaHandlerServiceRole01D49A7D:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - !Join 
          - ''
          - - 'arn:'
            - !Ref 'AWS::Partition'
            - ':iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
    Metadata:
      'aws:cdk:path': TheXrayHttpFlow/httpLambdaHandler/ServiceRole/Resource
  httpLambdaHandlerServiceRoleDefaultPolicy1B465FFF:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 'xray:PutTraceSegments'
              - 'xray:PutTelemetryRecords'
            Effect: Allow
            Resource: '*'
        Version: 2012-10-17
      PolicyName: httpLambdaHandlerServiceRoleDefaultPolicy1B465FFF
      Roles:
        - !Ref httpLambdaHandlerServiceRole01D49A7D
    Metadata:
      'aws:cdk:path': TheXrayHttpFlow/httpLambdaHandler/ServiceRole/DefaultPolicy/Resource
  httpLambdaHandler66D9C9A8:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: !Ref >-
          AssetParameters4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04bS3BucketFEB1737B
        S3Key: !Join 
          - ''
          - - !Select 
              - 0
              - !Split 
                - '||'
                - !Ref >-
                  AssetParameters4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04bS3VersionKey433D325F
            - !Select 
              - 1
              - !Split 
                - '||'
                - !Ref >-
                  AssetParameters4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04bS3VersionKey433D325F
      Handler: http.handler
      Role: !GetAtt 
        - httpLambdaHandlerServiceRole01D49A7D
        - Arn
      Runtime: nodejs12.x
      TracingConfig:
        Mode: Active
    DependsOn:
      - httpLambdaHandlerServiceRoleDefaultPolicy1B465FFF
      - httpLambdaHandlerServiceRole01D49A7D
    Metadata:
      'aws:cdk:path': TheXrayHttpFlow/httpLambdaHandler/Resource
      'aws:asset:path': asset.4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04b
      'aws:asset:property': Code
  httpLambdaHandlerAllowInvokeTheXrayHttpFlowSNSTopic4903AFE806D4343B:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt 
        - httpLambdaHandler66D9C9A8
        - Arn
      Principal: sns.amazonaws.com
      SourceArn: !ImportValue >-
        TheXrayTracerStack:ExportsOutputRefTheXRayTracerSnsFanOutTopicDE7E70F8D479F0D6
    Metadata:
      'aws:cdk:path': >-
        TheXrayHttpFlow/httpLambdaHandler/AllowInvoke:TheXrayHttpFlowSNSTopic4903AFE8
  httpLambdaHandlerSNSTopicEE70E0D4:
    Type: 'AWS::SNS::Subscription'
    Properties:
      Protocol: lambda
      TopicArn: !ImportValue >-
        TheXrayTracerStack:ExportsOutputRefTheXRayTracerSnsFanOutTopicDE7E70F8D479F0D6
      Endpoint: !GetAtt 
        - httpLambdaHandler66D9C9A8
        - Arn
    Metadata:
      'aws:cdk:path': TheXrayHttpFlow/httpLambdaHandler/SNSTopic/Resource
Parameters:
  AssetParameters4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04bS3BucketFEB1737B:
    Type: String
    Description: >-
      S3 bucket for asset
      "4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04b"
  AssetParameters4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04bS3VersionKey433D325F:
    Type: String
    Description: >-
      S3 key for asset version
      "4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04b"
  AssetParameters4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04bArtifactHash92535D2D:
    Type: String
    Description: >-
      Artifact hash for asset
      "4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04b"
