Resources:
  Queue4A7E3555:
    Type: 'AWS::SQS::Queue'
    Properties:
      VisibilityTimeout: 300
    Metadata:
      'aws:cdk:path': TheXraySQSFlow/Queue/Resource
  sqsLambdaHandlerServiceRole2F57B7B5:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - !Join 
          - ''
          - - 'arn:'
            - !Ref 'AWS::Partition'
            - ':iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
    Metadata:
      'aws:cdk:path': TheXraySQSFlow/sqsLambdaHandler/ServiceRole/Resource
  sqsLambdaHandlerServiceRoleDefaultPolicyBB0CE949:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 'xray:PutTraceSegments'
              - 'xray:PutTelemetryRecords'
            Effect: Allow
            Resource: '*'
          - Action:
              - 'sqs:SendMessage'
              - 'sqs:GetQueueAttributes'
              - 'sqs:GetQueueUrl'
            Effect: Allow
            Resource: !GetAtt 
              - Queue4A7E3555
              - Arn
        Version: 2012-10-17
      PolicyName: sqsLambdaHandlerServiceRoleDefaultPolicyBB0CE949
      Roles:
        - !Ref sqsLambdaHandlerServiceRole2F57B7B5
    Metadata:
      'aws:cdk:path': TheXraySQSFlow/sqsLambdaHandler/ServiceRole/DefaultPolicy/Resource
  sqsLambdaHandler0DD5DF9B:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: !Ref >-
          AssetParameters4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04bS3BucketFEB1737B
        S3Key: !Join 
          - ''
          - - !Select 
              - 0
              - !Split 
                - '||'
                - !Ref >-
                  AssetParameters4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04bS3VersionKey433D325F
            - !Select 
              - 1
              - !Split 
                - '||'
                - !Ref >-
                  AssetParameters4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04bS3VersionKey433D325F
      Handler: sqs.handler
      Role: !GetAtt 
        - sqsLambdaHandlerServiceRole2F57B7B5
        - Arn
      Runtime: nodejs12.x
      Environment:
        Variables:
          SQS_URL: !Ref Queue4A7E3555
      TracingConfig:
        Mode: Active
    DependsOn:
      - sqsLambdaHandlerServiceRoleDefaultPolicyBB0CE949
      - sqsLambdaHandlerServiceRole2F57B7B5
    Metadata:
      'aws:cdk:path': TheXraySQSFlow/sqsLambdaHandler/Resource
      'aws:asset:path': asset.4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04b
      'aws:asset:property': Code
  sqsLambdaHandlerAllowInvokeTheXraySQSFlowSNSTopicA671E652005D4F97:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt 
        - sqsLambdaHandler0DD5DF9B
        - Arn
      Principal: sns.amazonaws.com
      SourceArn: !ImportValue >-
        TheXrayTracerStack:ExportsOutputRefTheXRayTracerSnsFanOutTopicDE7E70F8D479F0D6
    Metadata:
      'aws:cdk:path': >-
        TheXraySQSFlow/sqsLambdaHandler/AllowInvoke:TheXraySQSFlowSNSTopicA671E652
  sqsLambdaHandlerSNSTopicC33599CE:
    Type: 'AWS::SNS::Subscription'
    Properties:
      Protocol: lambda
      TopicArn: !ImportValue >-
        TheXrayTracerStack:ExportsOutputRefTheXRayTracerSnsFanOutTopicDE7E70F8D479F0D6
      Endpoint: !GetAtt 
        - sqsLambdaHandler0DD5DF9B
        - Arn
    Metadata:
      'aws:cdk:path': TheXraySQSFlow/sqsLambdaHandler/SNSTopic/Resource
  SQSSubscribeLambdaHandlerServiceRoleB6261F09:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - !Join 
          - ''
          - - 'arn:'
            - !Ref 'AWS::Partition'
            - ':iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
    Metadata:
      'aws:cdk:path': TheXraySQSFlow/SQSSubscribeLambdaHandler/ServiceRole/Resource
  SQSSubscribeLambdaHandlerServiceRoleDefaultPolicy828D90B1:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 'xray:PutTraceSegments'
              - 'xray:PutTelemetryRecords'
            Effect: Allow
            Resource: '*'
          - Action:
              - 'sqs:ReceiveMessage'
              - 'sqs:ChangeMessageVisibility'
              - 'sqs:GetQueueUrl'
              - 'sqs:DeleteMessage'
              - 'sqs:GetQueueAttributes'
            Effect: Allow
            Resource: !GetAtt 
              - Queue4A7E3555
              - Arn
        Version: 2012-10-17
      PolicyName: SQSSubscribeLambdaHandlerServiceRoleDefaultPolicy828D90B1
      Roles:
        - !Ref SQSSubscribeLambdaHandlerServiceRoleB6261F09
    Metadata:
      'aws:cdk:path': >-
        TheXraySQSFlow/SQSSubscribeLambdaHandler/ServiceRole/DefaultPolicy/Resource
  SQSSubscribeLambdaHandlerBBB58615:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: !Ref >-
          AssetParameters4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04bS3BucketFEB1737B
        S3Key: !Join 
          - ''
          - - !Select 
              - 0
              - !Split 
                - '||'
                - !Ref >-
                  AssetParameters4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04bS3VersionKey433D325F
            - !Select 
              - 1
              - !Split 
                - '||'
                - !Ref >-
                  AssetParameters4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04bS3VersionKey433D325F
      Handler: sqs_subscribe.handler
      Role: !GetAtt 
        - SQSSubscribeLambdaHandlerServiceRoleB6261F09
        - Arn
      Runtime: nodejs12.x
      Environment:
        Variables:
          queueURL: !Ref Queue4A7E3555
      ReservedConcurrentExecutions: 2
      TracingConfig:
        Mode: Active
    DependsOn:
      - SQSSubscribeLambdaHandlerServiceRoleDefaultPolicy828D90B1
      - SQSSubscribeLambdaHandlerServiceRoleB6261F09
    Metadata:
      'aws:cdk:path': TheXraySQSFlow/SQSSubscribeLambdaHandler/Resource
      'aws:asset:path': asset.4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04b
      'aws:asset:property': Code
  SQSSubscribeLambdaHandlerSqsEventSourceTheXraySQSFlowQueue7994C13E575F6E73:
    Type: 'AWS::Lambda::EventSourceMapping'
    Properties:
      EventSourceArn: !GetAtt 
        - Queue4A7E3555
        - Arn
      FunctionName: !Ref SQSSubscribeLambdaHandlerBBB58615
    Metadata:
      'aws:cdk:path': >-
        TheXraySQSFlow/SQSSubscribeLambdaHandler/SqsEventSource:TheXraySQSFlowQueue7994C13E/Resource
Parameters:
  AssetParameters4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04bS3BucketFEB1737B:
    Type: String
    Description: >-
      S3 bucket for asset
      "4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04b"
  AssetParameters4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04bS3VersionKey433D325F:
    Type: String
    Description: >-
      S3 key for asset version
      "4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04b"
  AssetParameters4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04bArtifactHash92535D2D:
    Type: String
    Description: >-
      Artifact hash for asset
      "4f78fd1f05a29f6ed80acaaf918f6337a7e9be2d13311f31f93ad08228d0a04b"
