Resources:
  TheXRayTracerSnsFanOutTopicDE7E70F8:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: The XRay Tracer Fan Out Topic
    Metadata:
      'aws:cdk:path': TheXrayTracerStack/TheXRayTracerSnsFanOutTopic/Resource
  xrayTracerAPIA84CAE80:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: xrayTracerAPI
    Metadata:
      'aws:cdk:path': TheXrayTracerStack/xrayTracerAPI/Resource
  xrayTracerAPIDeploymentB3CB89A0a689bf68bef2302d0715c2d1a50794fc:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref xrayTracerAPIA84CAE80
      Description: Automatically created by the RestApi construct
    DependsOn:
      - xrayTracerAPIproxyGET4E348609
      - xrayTracerAPIproxy719DA214
      - xrayTracerAPIGET7490A366
      - xrayTracerAPIErrorResponseModel24719E91
      - xrayTracerAPIResponseModel2591E14E
    Metadata:
      'aws:cdk:path': TheXrayTracerStack/xrayTracerAPI/Deployment/Resource
  xrayTracerAPIDeploymentStageprod85442A48:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      RestApiId: !Ref xrayTracerAPIA84CAE80
      DeploymentId: !Ref xrayTracerAPIDeploymentB3CB89A0a689bf68bef2302d0715c2d1a50794fc
      MethodSettings:
        - DataTraceEnabled: true
          HttpMethod: '*'
          LoggingLevel: INFO
          MetricsEnabled: true
          ResourcePath: /*
      StageName: prod
      TracingEnabled: true
    Metadata:
      'aws:cdk:path': TheXrayTracerStack/xrayTracerAPI/DeploymentStage.prod/Resource
  xrayTracerAPICloudWatchRoleCCB113F4:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - !Join 
          - ''
          - - 'arn:'
            - !Ref 'AWS::Partition'
            - ':iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs'
    Metadata:
      'aws:cdk:path': TheXrayTracerStack/xrayTracerAPI/CloudWatchRole/Resource
  xrayTracerAPIAccount092EDE74:
    Type: 'AWS::ApiGateway::Account'
    Properties:
      CloudWatchRoleArn: !GetAtt 
        - xrayTracerAPICloudWatchRoleCCB113F4
        - Arn
    DependsOn:
      - xrayTracerAPIA84CAE80
    Metadata:
      'aws:cdk:path': TheXrayTracerStack/xrayTracerAPI/Account
  xrayTracerAPIGET7490A366:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      HttpMethod: GET
      ResourceId: !GetAtt 
        - xrayTracerAPIA84CAE80
        - RootResourceId
      RestApiId: !Ref xrayTracerAPIA84CAE80
      AuthorizationType: NONE
      Integration:
        Credentials: !GetAtt 
          - ApiGatewaySNSRole1BAAAE75
          - Arn
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - ResponseTemplates:
              application/json: '{"message":"message added to SNS topic"}'
            StatusCode: '200'
          - ResponseParameters:
              method.response.header.Content-Type: '''application/json'''
              method.response.header.Access-Control-Allow-Origin: '''*'''
              method.response.header.Access-Control-Allow-Credentials: '''true'''
            ResponseTemplates:
              application/json: >-
                {"state":"error","message":"$util.escapeJavaScript($input.path('$.errorMessage'))"}
            SelectionPattern: '^[Error].*'
            StatusCode: '400'
        PassthroughBehavior: NEVER
        RequestParameters:
          integration.request.header.Content-Type: '''application/x-www-form-urlencoded'''
        RequestTemplates:
          application/json: !Join 
            - ''
            - - Action=Publish&TargetArn=$util.urlEncode('
              - !Ref TheXRayTracerSnsFanOutTopicDE7E70F8
              - ''')&Message=$util.urlEncode($context.path)&Version=2010-03-31'
        Type: AWS
        Uri: 'arn:aws:apigateway:us-east-1:sns:path//'
      MethodResponses:
        - ResponseModels:
            application/json: !Ref xrayTracerAPIResponseModel2591E14E
          ResponseParameters:
            method.response.header.Content-Type: true
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Credentials: true
          StatusCode: '200'
        - ResponseModels:
            application/json: !Ref xrayTracerAPIErrorResponseModel24719E91
          ResponseParameters:
            method.response.header.Content-Type: true
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Credentials: true
          StatusCode: '400'
    Metadata:
      'aws:cdk:path': TheXrayTracerStack/xrayTracerAPI/Default/GET/Resource
  xrayTracerAPIproxy719DA214:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      ParentId: !GetAtt 
        - xrayTracerAPIA84CAE80
        - RootResourceId
      PathPart: '{proxy+}'
      RestApiId: !Ref xrayTracerAPIA84CAE80
    Metadata:
      'aws:cdk:path': 'TheXrayTracerStack/xrayTracerAPI/Default/{proxy+}/Resource'
  xrayTracerAPIproxyGET4E348609:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      HttpMethod: GET
      ResourceId: !Ref xrayTracerAPIproxy719DA214
      RestApiId: !Ref xrayTracerAPIA84CAE80
      AuthorizationType: NONE
      Integration:
        Credentials: !GetAtt 
          - ApiGatewaySNSRole1BAAAE75
          - Arn
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - ResponseTemplates:
              application/json: '{"message":"message added to SNS topic"}'
            StatusCode: '200'
          - ResponseParameters:
              method.response.header.Content-Type: '''application/json'''
              method.response.header.Access-Control-Allow-Origin: '''*'''
              method.response.header.Access-Control-Allow-Credentials: '''true'''
            ResponseTemplates:
              application/json: >-
                {"state":"error","message":"$util.escapeJavaScript($input.path('$.errorMessage'))"}
            SelectionPattern: '^[Error].*'
            StatusCode: '400'
        PassthroughBehavior: NEVER
        RequestParameters:
          integration.request.header.Content-Type: '''application/x-www-form-urlencoded'''
        RequestTemplates:
          application/json: !Join 
            - ''
            - - Action=Publish&TargetArn=$util.urlEncode('
              - !Ref TheXRayTracerSnsFanOutTopicDE7E70F8
              - ''')&Message=$util.urlEncode($context.path)&Version=2010-03-31'
        Type: AWS
        Uri: 'arn:aws:apigateway:us-east-1:sns:path//'
      MethodResponses:
        - ResponseModels:
            application/json: !Ref xrayTracerAPIResponseModel2591E14E
          ResponseParameters:
            method.response.header.Content-Type: true
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Credentials: true
          StatusCode: '200'
        - ResponseModels:
            application/json: !Ref xrayTracerAPIErrorResponseModel24719E91
          ResponseParameters:
            method.response.header.Content-Type: true
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Credentials: true
          StatusCode: '400'
    Metadata:
      'aws:cdk:path': 'TheXrayTracerStack/xrayTracerAPI/Default/{proxy+}/GET/Resource'
  xrayTracerAPIResponseModel2591E14E:
    Type: 'AWS::ApiGateway::Model'
    Properties:
      RestApiId: !Ref xrayTracerAPIA84CAE80
      ContentType: application/json
      Name: ResponseModel
      Schema:
        $schema: 'http://json-schema.org/draft-04/schema#'
        title: pollResponse
        type: object
        properties:
          message:
            type: string
    Metadata:
      'aws:cdk:path': TheXrayTracerStack/xrayTracerAPI/ResponseModel/Resource
  xrayTracerAPIErrorResponseModel24719E91:
    Type: 'AWS::ApiGateway::Model'
    Properties:
      RestApiId: !Ref xrayTracerAPIA84CAE80
      ContentType: application/json
      Name: ErrorResponseModel
      Schema:
        $schema: 'http://json-schema.org/draft-04/schema#'
        title: errorResponse
        type: object
        properties:
          state:
            type: string
          message:
            type: string
    Metadata:
      'aws:cdk:path': TheXrayTracerStack/xrayTracerAPI/ErrorResponseModel/Resource
  ApiGatewaySNSRole1BAAAE75:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: 2012-10-17
    Metadata:
      'aws:cdk:path': TheXrayTracerStack/ApiGatewaySNSRole/Resource
  ApiGatewaySNSRoleDefaultPolicyCA5D0260:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action: 'sns:Publish'
            Effect: Allow
            Resource: !Ref TheXRayTracerSnsFanOutTopicDE7E70F8
        Version: 2012-10-17
      PolicyName: ApiGatewaySNSRoleDefaultPolicyCA5D0260
      Roles:
        - !Ref ApiGatewaySNSRole1BAAAE75
    Metadata:
      'aws:cdk:path': TheXrayTracerStack/ApiGatewaySNSRole/DefaultPolicy/Resource
Outputs:
  xrayTracerAPIEndpointA106537B:
    Value: !Join 
      - ''
      - - 'https://'
        - !Ref xrayTracerAPIA84CAE80
        - .execute-api.
        - !Ref 'AWS::Region'
        - .
        - !Ref 'AWS::URLSuffix'
        - /
        - !Ref xrayTracerAPIDeploymentStageprod85442A48
        - /
  ExportsOutputRefTheXRayTracerSnsFanOutTopicDE7E70F8D479F0D6:
    Value: !Ref TheXRayTracerSnsFanOutTopicDE7E70F8
    Export:
      Name: >-
        TheXrayTracerStack:ExportsOutputRefTheXRayTracerSnsFanOutTopicDE7E70F8D479F0D6