Resources:
  pineappleCheckLambdaHandlerServiceRoleFC4E3211:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: the-state-machine/pineappleCheckLambdaHandler/ServiceRole/Resource
  pineappleCheckLambdaHandlerFDB742D5:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameterscec15e5edfc667123f62920f33949c096931ed16d8aaaaaa74da8cea5101cd9aS3Bucket825E6857
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameterscec15e5edfc667123f62920f33949c096931ed16d8aaaaaa74da8cea5101cd9aS3VersionKeyC4B7B43D
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameterscec15e5edfc667123f62920f33949c096931ed16d8aaaaaa74da8cea5101cd9aS3VersionKeyC4B7B43D
      Handler: orderPizza.handler
      Role:
        Fn::GetAtt:
          - pineappleCheckLambdaHandlerServiceRoleFC4E3211
          - Arn
      Runtime: nodejs12.x
    DependsOn:
      - pineappleCheckLambdaHandlerServiceRoleFC4E3211
    Metadata:
      aws:cdk:path: the-state-machine/pineappleCheckLambdaHandler/Resource
      aws:asset:path: C:\Users\matco\Documents\nideveloper\serverless\the-state-machine\python\lambdas
      aws:asset:property: Code
  StateMachineRoleB840431D:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                Fn::Join:
                  - ""
                  - - states.
                    - Ref: AWS::Region
                    - .amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: the-state-machine/StateMachine/Role/Resource
  StateMachineRoleDefaultPolicyDF1E6607:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - pineappleCheckLambdaHandlerFDB742D5
                - Arn
        Version: "2012-10-17"
      PolicyName: StateMachineRoleDefaultPolicyDF1E6607
      Roles:
        - Ref: StateMachineRoleB840431D
    Metadata:
      aws:cdk:path: the-state-machine/StateMachine/Role/DefaultPolicy/Resource
  StateMachine2E01A3A5:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      DefinitionString:
        Fn::Join:
          - ""
          - - '{"StartAt":"Order Pizza Job","States":{"Order Pizza Job":{"Next":"With Pineapple?","InputPath":"$.flavour","Type":"Task","Resource":"'
            - Fn::GetAtt:
                - pineappleCheckLambdaHandlerFDB742D5
                - Arn
            - '","ResultPath":"$.pineappleAnalysis"},"With Pineapple?":{"Type":"Choice","Choices":[{"Variable":"$.pineappleAnalysis.containsPineapple","BooleanEquals":true,"Next":"Sorry, We Dont add Pineapple"}],"Default":"Lets make your pizza"},"Lets make your pizza":{"Type":"Pass","End":true},"Sorry, We Dont add Pineapple":{"Type":"Fail","Error":"They asked for Pineapple","Cause":"Failed To Make Pizza"}},"TimeoutSeconds":300}'
      RoleArn:
        Fn::GetAtt:
          - StateMachineRoleB840431D
          - Arn
    DependsOn:
      - StateMachineRoleDefaultPolicyDF1E6607
      - StateMachineRoleB840431D
    Metadata:
      aws:cdk:path: the-state-machine/StateMachine/Resource
  stateMachineLambdaDLQ2E386ECB:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 300
    Metadata:
      aws:cdk:path: the-state-machine/stateMachineLambdaDLQ/Resource
  stateMachineLambdaHandlerServiceRoleDEB9C06E:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: the-state-machine/stateMachineLambdaHandler/ServiceRole/Resource
  stateMachineLambdaHandlerServiceRoleDefaultPolicyEFBA4308:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: states:StartExecution
            Effect: Allow
            Resource:
              Ref: StateMachine2E01A3A5
        Version: "2012-10-17"
      PolicyName: stateMachineLambdaHandlerServiceRoleDefaultPolicyEFBA4308
      Roles:
        - Ref: stateMachineLambdaHandlerServiceRoleDEB9C06E
    Metadata:
      aws:cdk:path: the-state-machine/stateMachineLambdaHandler/ServiceRole/DefaultPolicy/Resource
  stateMachineLambdaHandler8A4FAE4C:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameterscec15e5edfc667123f62920f33949c096931ed16d8aaaaaa74da8cea5101cd9aS3Bucket825E6857
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameterscec15e5edfc667123f62920f33949c096931ed16d8aaaaaa74da8cea5101cd9aS3VersionKeyC4B7B43D
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameterscec15e5edfc667123f62920f33949c096931ed16d8aaaaaa74da8cea5101cd9aS3VersionKeyC4B7B43D
      Handler: stateMachineLambda.handler
      Role:
        Fn::GetAtt:
          - stateMachineLambdaHandlerServiceRoleDEB9C06E
          - Arn
      Runtime: nodejs12.x
      Environment:
        Variables:
          statemachine_arn:
            Ref: StateMachine2E01A3A5
    DependsOn:
      - stateMachineLambdaHandlerServiceRoleDefaultPolicyEFBA4308
      - stateMachineLambdaHandlerServiceRoleDEB9C06E
    Metadata:
      aws:cdk:path: the-state-machine/stateMachineLambdaHandler/Resource
      aws:asset:path: C:\Users\matco\Documents\nideveloper\serverless\the-state-machine\python\lambdas
      aws:asset:property: Code
  EndpointEEF1FD8F:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: Endpoint
    Metadata:
      aws:cdk:path: the-state-machine/Endpoint/Resource
  EndpointDeployment318525DAc90cb9b5fbfaca8ef48f374aa6a5c8f5:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: EndpointEEF1FD8F
      Description: Automatically created by the RestApi construct
    DependsOn:
      - EndpointproxyANYC09721C5
      - Endpointproxy39E2174E
      - EndpointANY485C938B
    Metadata:
      aws:cdk:path: the-state-machine/Endpoint/Deployment/Resource
  EndpointDeploymentStageprodB78BEEA0:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: EndpointEEF1FD8F
      DeploymentId:
        Ref: EndpointDeployment318525DAc90cb9b5fbfaca8ef48f374aa6a5c8f5
      StageName: prod
    Metadata:
      aws:cdk:path: the-state-machine/Endpoint/DeploymentStage.prod/Resource
  EndpointCloudWatchRoleC3C64E0F:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: the-state-machine/Endpoint/CloudWatchRole/Resource
  EndpointAccountB8304247:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - EndpointCloudWatchRoleC3C64E0F
          - Arn
    DependsOn:
      - EndpointEEF1FD8F
    Metadata:
      aws:cdk:path: the-state-machine/Endpoint/Account
  Endpointproxy39E2174E:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - EndpointEEF1FD8F
          - RootResourceId
      PathPart: "{proxy+}"
      RestApiId:
        Ref: EndpointEEF1FD8F
    Metadata:
      aws:cdk:path: the-state-machine/Endpoint/Default/{proxy+}/Resource
  EndpointproxyANYApiPermissionthestatemachineEndpointF119963EANYproxy11116D58:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - stateMachineLambdaHandler8A4FAE4C
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /
            - Ref: EndpointDeploymentStageprodB78BEEA0
            - /*/{proxy+}
    Metadata:
      aws:cdk:path: the-state-machine/Endpoint/Default/{proxy+}/ANY/ApiPermission.thestatemachineEndpointF119963E.ANY..{proxy+}
  EndpointproxyANYApiPermissionTestthestatemachineEndpointF119963EANYproxy2C2E26B5:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - stateMachineLambdaHandler8A4FAE4C
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /test-invoke-stage/*/{proxy+}
    Metadata:
      aws:cdk:path: the-state-machine/Endpoint/Default/{proxy+}/ANY/ApiPermission.Test.thestatemachineEndpointF119963E.ANY..{proxy+}
  EndpointproxyANYC09721C5:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Ref: Endpointproxy39E2174E
      RestApiId:
        Ref: EndpointEEF1FD8F
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - stateMachineLambdaHandler8A4FAE4C
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: the-state-machine/Endpoint/Default/{proxy+}/ANY/Resource
  EndpointANYApiPermissionthestatemachineEndpointF119963EANY121B8AEA:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - stateMachineLambdaHandler8A4FAE4C
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /
            - Ref: EndpointDeploymentStageprodB78BEEA0
            - /*/
    Metadata:
      aws:cdk:path: the-state-machine/Endpoint/Default/ANY/ApiPermission.thestatemachineEndpointF119963E.ANY..
  EndpointANYApiPermissionTestthestatemachineEndpointF119963EANY9E102811:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - stateMachineLambdaHandler8A4FAE4C
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /test-invoke-stage/*/
    Metadata:
      aws:cdk:path: the-state-machine/Endpoint/Default/ANY/ApiPermission.Test.thestatemachineEndpointF119963E.ANY..
  EndpointANY485C938B:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Fn::GetAtt:
          - EndpointEEF1FD8F
          - RootResourceId
      RestApiId:
        Ref: EndpointEEF1FD8F
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - stateMachineLambdaHandler8A4FAE4C
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: the-state-machine/Endpoint/Default/ANY/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.23.0,@aws-cdk/assets=1.23.0,@aws-cdk/aws-apigateway=1.23.0,@aws-cdk/aws-applicationautoscaling=1.23.0,@aws-cdk/aws-autoscaling=1.23.0,@aws-cdk/aws-autoscaling-common=1.23.0,@aws-cdk/aws-autoscaling-hooktargets=1.23.0,@aws-cdk/aws-certificatemanager=1.23.0,@aws-cdk/aws-cloudformation=1.23.0,@aws-cdk/aws-cloudfront=1.23.0,@aws-cdk/aws-cloudwatch=1.23.0,@aws-cdk/aws-ec2=1.23.0,@aws-cdk/aws-ecr=1.23.0,@aws-cdk/aws-ecr-assets=1.23.0,@aws-cdk/aws-ecs=1.23.0,@aws-cdk/aws-elasticloadbalancing=1.23.0,@aws-cdk/aws-elasticloadbalancingv2=1.23.0,@aws-cdk/aws-events=1.23.0,@aws-cdk/aws-iam=1.23.0,@aws-cdk/aws-kms=1.23.0,@aws-cdk/aws-lambda=1.23.0,@aws-cdk/aws-logs=1.23.0,@aws-cdk/aws-route53=1.23.0,@aws-cdk/aws-route53-targets=1.23.0,@aws-cdk/aws-s3=1.23.0,@aws-cdk/aws-s3-assets=1.23.0,@aws-cdk/aws-sam=1.23.0,@aws-cdk/aws-secretsmanager=1.23.0,@aws-cdk/aws-servicediscovery=1.23.0,@aws-cdk/aws-sns=1.23.0,@aws-cdk/aws-sns-subscriptions=1.23.0,@aws-cdk/aws-sqs=1.23.0,@aws-cdk/aws-ssm=1.23.0,@aws-cdk/aws-stepfunctions=1.23.0,@aws-cdk/aws-stepfunctions-tasks=1.23.0,@aws-cdk/core=1.23.0,@aws-cdk/cx-api=1.23.0,@aws-cdk/region-info=1.23.0,jsii-runtime=Python/3.6.3
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameterscec15e5edfc667123f62920f33949c096931ed16d8aaaaaa74da8cea5101cd9aS3Bucket825E6857:
    Type: String
    Description: S3 bucket for asset "cec15e5edfc667123f62920f33949c096931ed16d8aaaaaa74da8cea5101cd9a"
  AssetParameterscec15e5edfc667123f62920f33949c096931ed16d8aaaaaa74da8cea5101cd9aS3VersionKeyC4B7B43D:
    Type: String
    Description: S3 key for asset version "cec15e5edfc667123f62920f33949c096931ed16d8aaaaaa74da8cea5101cd9a"
  AssetParameterscec15e5edfc667123f62920f33949c096931ed16d8aaaaaa74da8cea5101cd9aArtifactHashF3376ED1:
    Type: String
    Description: Artifact hash for asset "cec15e5edfc667123f62920f33949c096931ed16d8aaaaaa74da8cea5101cd9a"
Outputs:
  Endpoint8024A810:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: EndpointEEF1FD8F
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: EndpointDeploymentStageprodB78BEEA0
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

