Resources:
  addLambdaHandlerServiceRole37B65F50:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: the-fat-lambda-stack/addLambdaHandler/ServiceRole/Resource
  addLambdaHandler9017B0E5:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters74c556eefc3d3d17617c89241055a8266b84bc98ee40f28e9820a0003ba45468S3Bucket2718CC2C
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters74c556eefc3d3d17617c89241055a8266b84bc98ee40f28e9820a0003ba45468S3VersionKeyC8E44A4B
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters74c556eefc3d3d17617c89241055a8266b84bc98ee40f28e9820a0003ba45468S3VersionKeyC8E44A4B
      Handler: fatlambda.add
      Role:
        Fn::GetAtt:
          - addLambdaHandlerServiceRole37B65F50
          - Arn
      Runtime: python3.8
    DependsOn:
      - addLambdaHandlerServiceRole37B65F50
    Metadata:
      aws:cdk:path: the-fat-lambda-stack/addLambdaHandler/Resource
      aws:asset:path: asset.74c556eefc3d3d17617c89241055a8266b84bc98ee40f28e9820a0003ba45468
      aws:asset:property: Code
  subtractLambdaHandlerServiceRole4A6E4302:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: the-fat-lambda-stack/subtractLambdaHandler/ServiceRole/Resource
  subtractLambdaHandler5C3056BE:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters74c556eefc3d3d17617c89241055a8266b84bc98ee40f28e9820a0003ba45468S3Bucket2718CC2C
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters74c556eefc3d3d17617c89241055a8266b84bc98ee40f28e9820a0003ba45468S3VersionKeyC8E44A4B
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters74c556eefc3d3d17617c89241055a8266b84bc98ee40f28e9820a0003ba45468S3VersionKeyC8E44A4B
      Handler: fatlambda.subtract
      Role:
        Fn::GetAtt:
          - subtractLambdaHandlerServiceRole4A6E4302
          - Arn
      Runtime: python3.8
    DependsOn:
      - subtractLambdaHandlerServiceRole4A6E4302
    Metadata:
      aws:cdk:path: the-fat-lambda-stack/subtractLambdaHandler/Resource
      aws:asset:path: asset.74c556eefc3d3d17617c89241055a8266b84bc98ee40f28e9820a0003ba45468
      aws:asset:property: Code
  multiplyLambdaHandlerServiceRole902757A2:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: the-fat-lambda-stack/multiplyLambdaHandler/ServiceRole/Resource
  multiplyLambdaHandler7068AFA9:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters74c556eefc3d3d17617c89241055a8266b84bc98ee40f28e9820a0003ba45468S3Bucket2718CC2C
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters74c556eefc3d3d17617c89241055a8266b84bc98ee40f28e9820a0003ba45468S3VersionKeyC8E44A4B
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters74c556eefc3d3d17617c89241055a8266b84bc98ee40f28e9820a0003ba45468S3VersionKeyC8E44A4B
      Handler: fatlambda.multiply
      Role:
        Fn::GetAtt:
          - multiplyLambdaHandlerServiceRole902757A2
          - Arn
      Runtime: python3.8
    DependsOn:
      - multiplyLambdaHandlerServiceRole902757A2
    Metadata:
      aws:cdk:path: the-fat-lambda-stack/multiplyLambdaHandler/Resource
      aws:asset:path: asset.74c556eefc3d3d17617c89241055a8266b84bc98ee40f28e9820a0003ba45468
      aws:asset:property: Code
  fatLambdaAPIDE58F80F:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: fatLambdaAPI
    Metadata:
      aws:cdk:path: the-fat-lambda-stack/fatLambdaAPI/Resource
  fatLambdaAPIDeploymentAB28B6F29df611a5666c1c7f1e83de9efc6b516a:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: fatLambdaAPIDE58F80F
      Description: Automatically created by the RestApi construct
    DependsOn:
      - fatLambdaAPIaddGET0E753E34
      - fatLambdaAPIadd5163AE8B
      - fatLambdaAPImultiplyGET69DC6CC1
      - fatLambdaAPImultiplyDDE1F047
      - fatLambdaAPIsubtractGETCA4F04B1
      - fatLambdaAPIsubtract252EA067
    Metadata:
      aws:cdk:path: the-fat-lambda-stack/fatLambdaAPI/Deployment/Resource
  fatLambdaAPIDeploymentStageprod0C322274:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: fatLambdaAPIDE58F80F
      DeploymentId:
        Ref: fatLambdaAPIDeploymentAB28B6F29df611a5666c1c7f1e83de9efc6b516a
      StageName: prod
    Metadata:
      aws:cdk:path: the-fat-lambda-stack/fatLambdaAPI/DeploymentStage.prod/Resource
  fatLambdaAPICloudWatchRole1BD7739C:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: the-fat-lambda-stack/fatLambdaAPI/CloudWatchRole/Resource
  fatLambdaAPIAccount90F9D9B9:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - fatLambdaAPICloudWatchRole1BD7739C
          - Arn
    DependsOn:
      - fatLambdaAPIDE58F80F
    Metadata:
      aws:cdk:path: the-fat-lambda-stack/fatLambdaAPI/Account
  fatLambdaAPIadd5163AE8B:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - fatLambdaAPIDE58F80F
          - RootResourceId
      PathPart: add
      RestApiId:
        Ref: fatLambdaAPIDE58F80F
    Metadata:
      aws:cdk:path: the-fat-lambda-stack/fatLambdaAPI/Default/add/Resource
  fatLambdaAPIaddGETApiPermissionthefatlambdastackfatLambdaAPI36EE7B78GETadd861F0889:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - addLambdaHandler9017B0E5
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: fatLambdaAPIDE58F80F
            - /
            - Ref: fatLambdaAPIDeploymentStageprod0C322274
            - /GET/add
    Metadata:
      aws:cdk:path: the-fat-lambda-stack/fatLambdaAPI/Default/add/GET/ApiPermission.thefatlambdastackfatLambdaAPI36EE7B78.GET..add
  fatLambdaAPIaddGETApiPermissionTestthefatlambdastackfatLambdaAPI36EE7B78GETadd9075A419:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - addLambdaHandler9017B0E5
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: fatLambdaAPIDE58F80F
            - /test-invoke-stage/GET/add
    Metadata:
      aws:cdk:path: the-fat-lambda-stack/fatLambdaAPI/Default/add/GET/ApiPermission.Test.thefatlambdastackfatLambdaAPI36EE7B78.GET..add
  fatLambdaAPIaddGET0E753E34:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Ref: fatLambdaAPIadd5163AE8B
      RestApiId:
        Ref: fatLambdaAPIDE58F80F
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - addLambdaHandler9017B0E5
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: the-fat-lambda-stack/fatLambdaAPI/Default/add/GET/Resource
  fatLambdaAPIsubtract252EA067:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - fatLambdaAPIDE58F80F
          - RootResourceId
      PathPart: subtract
      RestApiId:
        Ref: fatLambdaAPIDE58F80F
    Metadata:
      aws:cdk:path: the-fat-lambda-stack/fatLambdaAPI/Default/subtract/Resource
  fatLambdaAPIsubtractGETApiPermissionthefatlambdastackfatLambdaAPI36EE7B78GETsubtractACCF343E:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - subtractLambdaHandler5C3056BE
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: fatLambdaAPIDE58F80F
            - /
            - Ref: fatLambdaAPIDeploymentStageprod0C322274
            - /GET/subtract
    Metadata:
      aws:cdk:path: the-fat-lambda-stack/fatLambdaAPI/Default/subtract/GET/ApiPermission.thefatlambdastackfatLambdaAPI36EE7B78.GET..subtract
  fatLambdaAPIsubtractGETApiPermissionTestthefatlambdastackfatLambdaAPI36EE7B78GETsubtract111C5042:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - subtractLambdaHandler5C3056BE
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: fatLambdaAPIDE58F80F
            - /test-invoke-stage/GET/subtract
    Metadata:
      aws:cdk:path: the-fat-lambda-stack/fatLambdaAPI/Default/subtract/GET/ApiPermission.Test.thefatlambdastackfatLambdaAPI36EE7B78.GET..subtract
  fatLambdaAPIsubtractGETCA4F04B1:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Ref: fatLambdaAPIsubtract252EA067
      RestApiId:
        Ref: fatLambdaAPIDE58F80F
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - subtractLambdaHandler5C3056BE
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: the-fat-lambda-stack/fatLambdaAPI/Default/subtract/GET/Resource
  fatLambdaAPImultiplyDDE1F047:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - fatLambdaAPIDE58F80F
          - RootResourceId
      PathPart: multiply
      RestApiId:
        Ref: fatLambdaAPIDE58F80F
    Metadata:
      aws:cdk:path: the-fat-lambda-stack/fatLambdaAPI/Default/multiply/Resource
  fatLambdaAPImultiplyGETApiPermissionthefatlambdastackfatLambdaAPI36EE7B78GETmultiply9201AEC1:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - multiplyLambdaHandler7068AFA9
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: fatLambdaAPIDE58F80F
            - /
            - Ref: fatLambdaAPIDeploymentStageprod0C322274
            - /GET/multiply
    Metadata:
      aws:cdk:path: the-fat-lambda-stack/fatLambdaAPI/Default/multiply/GET/ApiPermission.thefatlambdastackfatLambdaAPI36EE7B78.GET..multiply
  fatLambdaAPImultiplyGETApiPermissionTestthefatlambdastackfatLambdaAPI36EE7B78GETmultiply67BC3AB4:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - multiplyLambdaHandler7068AFA9
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: fatLambdaAPIDE58F80F
            - /test-invoke-stage/GET/multiply
    Metadata:
      aws:cdk:path: the-fat-lambda-stack/fatLambdaAPI/Default/multiply/GET/ApiPermission.Test.thefatlambdastackfatLambdaAPI36EE7B78.GET..multiply
  fatLambdaAPImultiplyGET69DC6CC1:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Ref: fatLambdaAPImultiplyDDE1F047
      RestApiId:
        Ref: fatLambdaAPIDE58F80F
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - multiplyLambdaHandler7068AFA9
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: the-fat-lambda-stack/fatLambdaAPI/Default/multiply/GET/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.31.0,@aws-cdk/assets=1.31.0,@aws-cdk/aws-apigateway=1.31.0,@aws-cdk/aws-certificatemanager=1.31.0,@aws-cdk/aws-cloudformation=1.31.0,@aws-cdk/aws-cloudwatch=1.31.0,@aws-cdk/aws-ec2=1.31.0,@aws-cdk/aws-elasticloadbalancingv2=1.31.0,@aws-cdk/aws-events=1.31.0,@aws-cdk/aws-iam=1.31.0,@aws-cdk/aws-kms=1.31.0,@aws-cdk/aws-lambda=1.31.0,@aws-cdk/aws-logs=1.31.0,@aws-cdk/aws-route53=1.31.0,@aws-cdk/aws-s3=1.31.0,@aws-cdk/aws-s3-assets=1.31.0,@aws-cdk/aws-sns=1.31.0,@aws-cdk/aws-sqs=1.31.0,@aws-cdk/aws-ssm=1.31.0,@aws-cdk/core=1.31.0,@aws-cdk/cx-api=1.31.0,@aws-cdk/region-info=1.31.0,jsii-runtime=Python/3.6.10
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters74c556eefc3d3d17617c89241055a8266b84bc98ee40f28e9820a0003ba45468S3Bucket2718CC2C:
    Type: String
    Description: S3 bucket for asset "74c556eefc3d3d17617c89241055a8266b84bc98ee40f28e9820a0003ba45468"
  AssetParameters74c556eefc3d3d17617c89241055a8266b84bc98ee40f28e9820a0003ba45468S3VersionKeyC8E44A4B:
    Type: String
    Description: S3 key for asset version "74c556eefc3d3d17617c89241055a8266b84bc98ee40f28e9820a0003ba45468"
  AssetParameters74c556eefc3d3d17617c89241055a8266b84bc98ee40f28e9820a0003ba45468ArtifactHash8900DC8D:
    Type: String
    Description: Artifact hash for asset "74c556eefc3d3d17617c89241055a8266b84bc98ee40f28e9820a0003ba45468"
Outputs:
  fatLambdaAPIEndpointF80F7646:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: fatLambdaAPIDE58F80F
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: fatLambdaAPIDeploymentStageprod0C322274
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

