Resources:
  HitsFF5AF8CD:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: path
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: path
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: TheSimpleWebserviceStack/Hits/Resource
  DynamoLambdaHandlerServiceRole4C867B01:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: TheSimpleWebserviceStack/DynamoLambdaHandler/ServiceRole/Resource
  DynamoLambdaHandlerServiceRoleDefaultPolicy2B40B090:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:Query
              - dynamodb:GetItem
              - dynamodb:Scan
              - dynamodb:BatchWriteItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - HitsFF5AF8CD
                  - Arn
              - Ref: AWS::NoValue
        Version: "2012-10-17"
      PolicyName: DynamoLambdaHandlerServiceRoleDefaultPolicy2B40B090
      Roles:
        - Ref: DynamoLambdaHandlerServiceRole4C867B01
    Metadata:
      aws:cdk:path: TheSimpleWebserviceStack/DynamoLambdaHandler/ServiceRole/DefaultPolicy/Resource
  DynamoLambdaHandlerFB6EB814:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters021253fe8de19c6f70b8f1ca7aa029c7241fec35aa1f6aaced688781b661962bS3Bucket714B14B3
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters021253fe8de19c6f70b8f1ca7aa029c7241fec35aa1f6aaced688781b661962bS3VersionKey2D58A242
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters021253fe8de19c6f70b8f1ca7aa029c7241fec35aa1f6aaced688781b661962bS3VersionKey2D58A242
      Handler: lambda.handler
      Role:
        Fn::GetAtt:
          - DynamoLambdaHandlerServiceRole4C867B01
          - Arn
      Runtime: nodejs12.x
      Environment:
        Variables:
          HITS_TABLE_NAME:
            Ref: HitsFF5AF8CD
    DependsOn:
      - DynamoLambdaHandlerServiceRoleDefaultPolicy2B40B090
      - DynamoLambdaHandlerServiceRole4C867B01
    Metadata:
      aws:cdk:path: TheSimpleWebserviceStack/DynamoLambdaHandler/Resource
      aws:asset:path: C:\Users\matco\Documents\nideveloper\serverless\the-simple-webservice\typescript\lambda
      aws:asset:property: Code
  EndpointEEF1FD8F:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: Endpoint
    Metadata:
      aws:cdk:path: TheSimpleWebserviceStack/Endpoint/Resource
  EndpointDeployment318525DAe471c4d691d27847a9322f9606f5f602:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: EndpointEEF1FD8F
      Description: Automatically created by the RestApi construct
    DependsOn:
      - EndpointproxyANYC09721C5
      - Endpointproxy39E2174E
      - EndpointANY485C938B
    Metadata:
      aws:cdk:path: TheSimpleWebserviceStack/Endpoint/Deployment/Resource
  EndpointDeploymentStageprodB78BEEA0:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: EndpointEEF1FD8F
      DeploymentId:
        Ref: EndpointDeployment318525DAe471c4d691d27847a9322f9606f5f602
      StageName: prod
    Metadata:
      aws:cdk:path: TheSimpleWebserviceStack/Endpoint/DeploymentStage.prod/Resource
  EndpointCloudWatchRoleC3C64E0F:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: TheSimpleWebserviceStack/Endpoint/CloudWatchRole/Resource
  EndpointAccountB8304247:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - EndpointCloudWatchRoleC3C64E0F
          - Arn
    DependsOn:
      - EndpointEEF1FD8F
    Metadata:
      aws:cdk:path: TheSimpleWebserviceStack/Endpoint/Account
  Endpointproxy39E2174E:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - EndpointEEF1FD8F
          - RootResourceId
      PathPart: "{proxy+}"
      RestApiId:
        Ref: EndpointEEF1FD8F
    Metadata:
      aws:cdk:path: TheSimpleWebserviceStack/Endpoint/Default/{proxy+}/Resource
  EndpointproxyANYApiPermissionTheSimpleWebserviceStackEndpoint4D88DB46ANYproxyB140B3BD:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - DynamoLambdaHandlerFB6EB814
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /
            - Ref: EndpointDeploymentStageprodB78BEEA0
            - /*/{proxy+}
    Metadata:
      aws:cdk:path: TheSimpleWebserviceStack/Endpoint/Default/{proxy+}/ANY/ApiPermission.TheSimpleWebserviceStackEndpoint4D88DB46.ANY..{proxy+}
  EndpointproxyANYApiPermissionTestTheSimpleWebserviceStackEndpoint4D88DB46ANYproxy08C79E50:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - DynamoLambdaHandlerFB6EB814
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /test-invoke-stage/*/{proxy+}
    Metadata:
      aws:cdk:path: TheSimpleWebserviceStack/Endpoint/Default/{proxy+}/ANY/ApiPermission.Test.TheSimpleWebserviceStackEndpoint4D88DB46.ANY..{proxy+}
  EndpointproxyANYC09721C5:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Ref: Endpointproxy39E2174E
      RestApiId:
        Ref: EndpointEEF1FD8F
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - DynamoLambdaHandlerFB6EB814
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: TheSimpleWebserviceStack/Endpoint/Default/{proxy+}/ANY/Resource
  EndpointANYApiPermissionTheSimpleWebserviceStackEndpoint4D88DB46ANY4125DEDB:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - DynamoLambdaHandlerFB6EB814
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /
            - Ref: EndpointDeploymentStageprodB78BEEA0
            - /*/
    Metadata:
      aws:cdk:path: TheSimpleWebserviceStack/Endpoint/Default/ANY/ApiPermission.TheSimpleWebserviceStackEndpoint4D88DB46.ANY..
  EndpointANYApiPermissionTestTheSimpleWebserviceStackEndpoint4D88DB46ANY2C1DB5A2:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - DynamoLambdaHandlerFB6EB814
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /test-invoke-stage/*/
    Metadata:
      aws:cdk:path: TheSimpleWebserviceStack/Endpoint/Default/ANY/ApiPermission.Test.TheSimpleWebserviceStackEndpoint4D88DB46.ANY..
  EndpointANY485C938B:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Fn::GetAtt:
          - EndpointEEF1FD8F
          - RootResourceId
      RestApiId:
        Ref: EndpointEEF1FD8F
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - DynamoLambdaHandlerFB6EB814
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: TheSimpleWebserviceStack/Endpoint/Default/ANY/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.23.0,@aws-cdk/assets=1.21.1,@aws-cdk/aws-apigateway=1.21.1,@aws-cdk/aws-applicationautoscaling=1.21.1,@aws-cdk/aws-autoscaling-common=1.21.1,@aws-cdk/aws-cloudwatch=1.21.1,@aws-cdk/aws-dynamodb=1.21.1,@aws-cdk/aws-ec2=1.21.1,@aws-cdk/aws-events=1.21.1,@aws-cdk/aws-iam=1.21.1,@aws-cdk/aws-kms=1.21.1,@aws-cdk/aws-lambda=1.21.1,@aws-cdk/aws-s3=1.21.1,@aws-cdk/aws-s3-assets=1.21.1,@aws-cdk/aws-sqs=1.21.1,@aws-cdk/aws-ssm=1.21.1,@aws-cdk/core=1.21.1,@aws-cdk/cx-api=1.21.1,@aws-cdk/region-info=1.21.1,jsii-runtime=node.js/v13.6.0
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters021253fe8de19c6f70b8f1ca7aa029c7241fec35aa1f6aaced688781b661962bS3Bucket714B14B3:
    Type: String
    Description: S3 bucket for asset "021253fe8de19c6f70b8f1ca7aa029c7241fec35aa1f6aaced688781b661962b"
  AssetParameters021253fe8de19c6f70b8f1ca7aa029c7241fec35aa1f6aaced688781b661962bS3VersionKey2D58A242:
    Type: String
    Description: S3 key for asset version "021253fe8de19c6f70b8f1ca7aa029c7241fec35aa1f6aaced688781b661962b"
  AssetParameters021253fe8de19c6f70b8f1ca7aa029c7241fec35aa1f6aaced688781b661962bArtifactHash80EDAA75:
    Type: String
    Description: Artifact hash for asset "021253fe8de19c6f70b8f1ca7aa029c7241fec35aa1f6aaced688781b661962b"
Outputs:
  Endpoint8024A810:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: EndpointEEF1FD8F
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: EndpointDeploymentStageprodB78BEEA0
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

