Resources:
  HitsFF5AF8CD:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: path
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: path
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: the-simple-webservice/Hits/Resource
  DynamoLambdaHandlerServiceRole4C867B01:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: the-simple-webservice/DynamoLambdaHandler/ServiceRole/Resource
  DynamoLambdaHandlerServiceRoleDefaultPolicy2B40B090:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:Query
              - dynamodb:GetItem
              - dynamodb:Scan
              - dynamodb:BatchWriteItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - HitsFF5AF8CD
                  - Arn
              - Ref: AWS::NoValue
        Version: "2012-10-17"
      PolicyName: DynamoLambdaHandlerServiceRoleDefaultPolicy2B40B090
      Roles:
        - Ref: DynamoLambdaHandlerServiceRole4C867B01
    Metadata:
      aws:cdk:path: the-simple-webservice/DynamoLambdaHandler/ServiceRole/DefaultPolicy/Resource
  DynamoLambdaHandlerFB6EB814:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameterseeeeb6d62dae5f117629d60af86cb2ad7643afd457833c89a457f4ff0062940bS3Bucket1D74099F
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameterseeeeb6d62dae5f117629d60af86cb2ad7643afd457833c89a457f4ff0062940bS3VersionKey69EF49BE
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameterseeeeb6d62dae5f117629d60af86cb2ad7643afd457833c89a457f4ff0062940bS3VersionKey69EF49BE
      Handler: lambda.handler
      Role:
        Fn::GetAtt:
          - DynamoLambdaHandlerServiceRole4C867B01
          - Arn
      Runtime: nodejs12.x
      Environment:
        Variables:
          HITS_TABLE_NAME:
            Ref: HitsFF5AF8CD
    DependsOn:
      - DynamoLambdaHandlerServiceRoleDefaultPolicy2B40B090
      - DynamoLambdaHandlerServiceRole4C867B01
    Metadata:
      aws:cdk:path: the-simple-webservice/DynamoLambdaHandler/Resource
      aws:asset:path: asset.eeeeb6d62dae5f117629d60af86cb2ad7643afd457833c89a457f4ff0062940b
      aws:asset:property: Code
  DynamoLambdaHandlerthesimplewebserviceEndpointDefaultRouteDFFE769DPermissionC0BB4C3A:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - DynamoLambdaHandlerFB6EB814
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /*/*
    Metadata:
      aws:cdk:path: the-simple-webservice/DynamoLambdaHandler/thesimplewebserviceEndpointDefaultRouteDFFE769D-Permission
  EndpointEEF1FD8F:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: Endpoint
      ProtocolType: HTTP
    Metadata:
      aws:cdk:path: the-simple-webservice/Endpoint/Resource
  EndpointDefaultRouteDefaultRouteIntegration4584A785:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: EndpointEEF1FD8F
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::GetAtt:
          - DynamoLambdaHandlerFB6EB814
          - Arn
      PayloadFormatVersion: "2.0"
    Metadata:
      aws:cdk:path: the-simple-webservice/Endpoint/DefaultRoute/DefaultRoute-Integration/Resource
  EndpointDefaultRouteB7B22F2B:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: EndpointEEF1FD8F
      RouteKey: $default
      Target:
        Fn::Join:
          - ""
          - - integrations/
            - Ref: EndpointDefaultRouteDefaultRouteIntegration4584A785
    Metadata:
      aws:cdk:path: the-simple-webservice/Endpoint/DefaultRoute/Resource
  EndpointDefaultStage0AD21F27:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId:
        Ref: EndpointEEF1FD8F
      StageName: $default
      AutoDeploy: true
    Metadata:
      aws:cdk:path: the-simple-webservice/Endpoint/DefaultStage/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.36.1,@aws-cdk/assets=1.37.0,@aws-cdk/aws-apigatewayv2=1.37.0,@aws-cdk/aws-applicationautoscaling=1.37.0,@aws-cdk/aws-autoscaling-common=1.37.0,@aws-cdk/aws-cloudformation=1.37.0,@aws-cdk/aws-cloudwatch=1.37.0,@aws-cdk/aws-dynamodb=1.37.0,@aws-cdk/aws-ec2=1.37.0,@aws-cdk/aws-events=1.37.0,@aws-cdk/aws-iam=1.37.0,@aws-cdk/aws-kms=1.37.0,@aws-cdk/aws-lambda=1.37.0,@aws-cdk/aws-logs=1.37.0,@aws-cdk/aws-s3=1.37.0,@aws-cdk/aws-s3-assets=1.37.0,@aws-cdk/aws-sns=1.37.0,@aws-cdk/aws-sqs=1.37.0,@aws-cdk/aws-ssm=1.37.0,@aws-cdk/cloud-assembly-schema=1.37.0,@aws-cdk/core=1.37.0,@aws-cdk/custom-resources=1.37.0,@aws-cdk/cx-api=1.37.0,@aws-cdk/region-info=1.37.0,jsii-runtime=Python/3.6.10
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameterseeeeb6d62dae5f117629d60af86cb2ad7643afd457833c89a457f4ff0062940bS3Bucket1D74099F:
    Type: String
    Description: S3 bucket for asset "eeeeb6d62dae5f117629d60af86cb2ad7643afd457833c89a457f4ff0062940b"
  AssetParameterseeeeb6d62dae5f117629d60af86cb2ad7643afd457833c89a457f4ff0062940bS3VersionKey69EF49BE:
    Type: String
    Description: S3 key for asset version "eeeeb6d62dae5f117629d60af86cb2ad7643afd457833c89a457f4ff0062940b"
  AssetParameterseeeeb6d62dae5f117629d60af86cb2ad7643afd457833c89a457f4ff0062940bArtifactHashB16DE2BD:
    Type: String
    Description: Artifact hash for asset "eeeeb6d62dae5f117629d60af86cb2ad7643afd457833c89a457f4ff0062940b"
Outputs:
  HTTPAPIUrl:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: EndpointEEF1FD8F
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

